version: '2'
services:
    base:
        image: dummy
        working_dir: /mnt/scraps
        volumes:
            - .:/mnt/scraps
    linux-env:
        extends:
            service: base
        image: bittorrent/live-build-environments:linux-c65d648
    android-env:
        extends:
            service: base
        image: bittorrent/live-build-environments:android-n17-s25-arm-6a57cdd
        environment:
            - SCRAPS_CROSS_TARGET=android
